### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grevelem/TC359project10#1]
Instead of:

``` ruby
validates :age, length: { is: 2 }
```

I think a validation that makes more sense for age is that it has a minimum (whatever the minimum age of these baseball players is). See if [this resource](http://stackoverflow.com/questions/4416278/how-to-implement-min-max-validator-in-rails-3) can help you figure out how you'd do that.

**Comment by grevelem** [comment]
Hey Professor Fritz, I think I got it working correctly with the following: Makes a little more sense with the restrictions. Let me know if further work needs to be done! Thanks!
validates_numericality_of :age, less_than_or_equal_to: 24, greater_than: 17

**Comment by chrisvfritz** [comment]
:+1: Looks great!
